/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/analytics-delivery/wrangler.jsonc --env=qa --include-runtime=false --strict-vars=false workers/analytics-delivery/worker-configuration.d.ts` (hash: 4f94d15725b4e937b2d1342fb66d8ec2)
interface __BaseEnv_Env {
	DB: D1Database;
	ENVIRONMENT: string;
	DELIVERY_ENABLED: string;
	GA4_MEASUREMENT_ID: string;
	DEBUG_EVENTS: string;
	GA4_API_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "DELIVERY_ENABLED" | "GA4_MEASUREMENT_ID" | "DEBUG_EVENTS" | "GA4_API_SECRET">> {}
}
