/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=qa --include-runtime=false --strict-vars=false` (hash: f0941678600f8201ecc3765a0bc51da4)
interface __BaseEnv_Env {
	DB: D1Database;
	ENVIRONMENT: string;
	VOICE_DEADLINES_ENABLED: string;
	OPENAI_API_KEY: string;
	VOICE_DEADLINES: DurableObjectNamespace<import("./src/index").VoiceDeadline>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "VoiceDeadline";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "VOICE_DEADLINES_ENABLED" | "OPENAI_API_KEY">> {}
}
